apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-application
  namespace: argocd   # Must be the same namespace where ArgoCD is installed
spec:
  project: default

  source:
    repoURL: https://github.com/LauraOkafor/argocd-app-config.git
    targetRevision: HEAD
    path: dev  # Folder in your repo containing YAMLs

  destination:
    server: https://kubernetes.default.svc  # This means deploy to the current cluster
    namespace: myapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:      # Automatically sync changes from Git
      prune: true   # Remove resources no longer defined in Git
      selfHeal: true  # Revert any out-of-sync changes in the cluster